### ISSUE TITLE
Document float/double algorithms

### ISSUE THREAD

**Issue by dubzzz** [dubzzz/pure-rand#640]
How to generate floats or doubles out of an integer value?

Note: We have snippets doing so in fast-check

**Comment by smohanty92** [comment]
> How to generate floats or doubles out of an integer value?
> 
> Note: We have snippets doing so in fast-check

Hi! Where can I find the snippets?

**Comment by dubzzz** [comment]
From https://fast-check.dev/docs/core-blocks/arbitraries/primitives/number/#float:

```js
fc.noBias(fc.integer({ min: 0, max: (1 << 24) - 1 }).map((v) => v / (1 << 24)));
```

From https://fast-check.dev/docs/core-blocks/arbitraries/primitives/number/#double:

```js
fc.noBias(
  fc
    .tuple(fc.integer({ min: 0, max: (1 << 26) - 1 }), fc.integer({ min: 0, max: (1 << 27) - 1 }))
    .map((v) => (v[0] * Math.pow(2, 27) + v[1]) * Math.pow(2, -53)),
);
```

**Comment by smohanty92** [comment]
> ```js
> fc.noBias(fc.integer({ min: 0, max: (1 << 24) - 1 }).map((v) => v / (1 << 24)));
> ```

Thanks!

I'm just doing `import fc from 'fast-check'
fc.noBias(fc.integer({ min: 0, max: (1 << 24) - 1 }).map((v) => v / (1 << 24)));`

But get  `fc.noBias is not a function`

I installed with pnpm and can see the `Arbitrary` class within fc

**Comment by dubzzz** [comment]
No need to use fast-check if the only thing you need is to generate random floating point value. My example with fast-check was just a quick extract of a code doing the conversion of an integer value to a floating point one.

Regarding `noBias`, the `fc.noBias` has not been rolled-out yet. For now it should be `fc.integer({ min: 0, max: (1 << 24) - 1 }).noBias().map((v) => v / (1 << 24))`.

**Comment by smohanty92** [comment]
> ```js
> map((v) => v / (1 << 24)));
> ```

Thanks for the clarification.

I had tried that int method and it worked. 
I also did,

`import fc from 'fast-check'
const min = 1.5;
const max = 5.7;

const min32 = Math.fround(min);
const max32 = Math.fround(max);

// Generate a random float within the specified range
const randomFloatArbitrary = fc.float({ min: min32, max: max32 }).noBias()
const randomFloat = fc.sample(randomFloatArbitrary, 1, { seed: 42})[0];
console.log(randomFloat);`

and that seemed to work just fine too.

**Comment by dubzzz** [comment]
Documentation of pure-rand updated at: https://github.com/dubzzz/pure-rand/pull/715

**Comment by vincerubinetti** [comment]
> Yes, please add. Baffling to have a prng library with no way of generating floats.

I am also curious why this is not built in. I do appreciate that a "recipe" is included in the readme (though at the end), but I'm curious as to the reason it's not just included as a utility function?

I'm imagining there's some mathematical/statistical reason for this. However I also see that the integer generating functions are all prefixed with `unsafe`. Perhaps this is a reference to something like them being not cyptographically safe? If so, perhaps the same logic could be used to name some float util functions, e.g. `unsafeFloat64`?

At the very least, some more discussion of these things in the readme for us non-cryptography experts would be appreciated 😇 ~The `unsafe` prefix isn't explained anywhere either.~ Just found [this discussion](https://github.com/dubzzz/pure-rand/discussions/555), but it really should be upfront in the readme (the main docs).
