### ISSUE TITLE
I cant get it to work

### ISSUE THREAD

**Issue by LowLevelSubmarine** [dubzzz/pure-rand#716]
## I am probably doing something stupid here
```JavaScript
function seededRandom(seed: number): number {
  const rng = prand.xoroshiro128plus(seed);
  const g1 = prand.unsafeUniformIntDistribution(0, (1 << 24) - 1, rng);
  return g1 / (1 << 24);
}

_.range(10).forEach((index) => {
  console.log(`${index}: ${seededRandom(index)}`)
})
```
The results i get dont look very distributed to me:
```
0: 0.9999999403953552
1: 0.9999998807907104
2: 0.9999998211860657
3: 0.9999997615814209
4: 0.9999997019767761
5: 0.9999996423721313
6: 0.9999995827674866
7: 0.9999995231628418
8: 0.999999463558197
9: 0.9999994039535522
```

**Comment by dubzzz** [comment]
You should not recreate a PRNG but ruse the same from one iteration to the other

**Comment by dubzzz** [comment]
Something like:

```js
function seededRandom(rng): number {
  const g1 = prand.unsafeUniformIntDistribution(0, (1 << 24) - 1, rng);
  return g1 / (1 << 24);
}

const rng = prand.xoroshiro128plus(0);
_.range(10).forEach((index) => {
  console.log(`${index}: ${seededRandom(rng)}`)
})
```

**Comment by LowLevelSubmarine** [comment]
Is there no way to get a consistent mapping from seed to a pseudo random number?

**Comment by dubzzz** [comment]
I don't get your point.

One point that is sure: It's not recommended to recreate a new PRNG for each generated value. It's known to be a bad usage of random number generators (not only with pure-rand, but also in other languages).

**Comment by dubzzz** [comment]
Not sure you can find any for this need. More precisely I think you probably address the issue wrongly from an architectural point of view.

The solution to get consistent results would be to have one PRNG for each distinct generation. Then you could seed pure-rand with something like: `Date.now() ^ (Math.random() * 0x100000000)`. Otherwise you can seed the generator once and them produce the next ones using jump.

**Comment by dubzzz** [comment]
The jumped option would be something like:

```js
function seededRandom(jumpedBy: number): number {
  let rng = prand.xoroshiro128plus(0);
  for (let i = 0 ; i !== jumpedBy ; ++i) {
    rng.unsafeJump();
  }
  const g1 = prand.unsafeUniformIntDistribution(0, (1 << 24) - 1, rng);
  return g1 / (1 << 24);
}

_.range(10).forEach((index) => {
  console.log(`${index}: ${seededRandom(index)}`)
})
```

**Comment by LowLevelSubmarine** [comment]
The snippet you've send is working for me. Thank you very much for the quick help!

**Comment by dubzzz** [comment]
You're welcome. But definitely jump is probably the best for your case. New seed it known to be an issue for such usages. Jumping on a given generator is way better to get independent simulations.
